name: couponzz
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  cached_network_image: ^2.0.0
  carousel_pro: ^1.0.0
  carousel_slider: ^1.4.1
  flutter_custom_clippers: ^1.1.0
  flutter_icons: ^1.0.0+1
  flutter_dash: ^0.0.1
  flutter_svg: ^0.14.0
  page_indicator: ^0.3.0
  rect_getter: 0.0.1
  flare_flutter: ^1.5.5
  wc_form_validators: ^0.1.1
  image_picker: ^0.6.5+2
  intl: ^0.16.1
  flutter_ticket_widget: ^0.0.1
  badges: ^1.1.1
  flutter_rating_bar:
  flat_icons_flutter: ^1.0.2
  searchable_dropdown: ^1.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/orders/mem1.png
    - images/orders/mem2.png
    - images/orders/mem3.png
    - images/orders/back.png
    - images/orders/i.png
    - images/orders/phone.png
    - images/orders/loc.png
    - images/menu/more.png

    - images/menu/fb.png
    - images/menu/messenger.png
    - images/menu/watsapp.png
    - images/referback.png
    - images/merchant/website.png
    - images/merchant/merchantimg.png
    - images/merchant/merchantback.png
    - images/profileicon/confirm.png
    - images/profileicon/down.png
    - images/profileicon/proBack.png
    - images/menu/arrowmenu.png
    - images/menu/menuLogo.png
    - images/menu/defaultImg.png
    - images/menu/menuback.png
    - images/menu/share.png
    - images/menu/hd1.png
    - images/menu/hd2.png
    - images/menu/hd3.png
    - images/menu/hd5.png
    - images/menu/hd6.png
    - images/menu/enter1.png
    - images/menu/faq.png
    - images/menu/edit.png
    - images/menu/next.png
    - images/menu/heart.png
    - images/menu/membership.png
    - images/menu/hdd.png
    - images/menu/tick.png
    - images/menu/order.png
    - images/menu/sale.png
    - images/menu/clothes.png
    - images/calendar.png
    - images/buy1.png
    - images/timer1.png
    - images/discounticon.png
    - images/location.png
    - images/storeicon.png
    - images/phone1.png
    - images/store1.png
    - images/store2.png
    - images/store3.png
    - images/store4.png
    - images/carou1.jpg
    - images/carou2.jpg
    - images/carou3.png
    - images/home.png
    - images/knowledge.png
    - images/couponshop.png
    - images/question1.png
    - images/buy1.png
    - images/user1.png
    - images/refer.png
    - images/loader.png
    - images/shoe.png
    - images/goggles.png
    - images/gift.png
    - images/tshirt.png
    - images/Mia.png
    - images/discount.png
    - images/logo2.png
    - images/logo3.jpeg
    - images/salad.png
    - images/sandwich.png
    - images/pint.png
    - images/fish.png
    - images/ice-cream.png
    - images/shopping-bag.png
    - images/fast.png
    - images/shp1.jpg
    - images/shp2.jpg
    - images/shp3.jpg
    - images/shp4.jpg


    - images/products/blazer1.jpeg
    - images/products/blazer2.jpeg
    - images/products/dress1.jpeg
    - images/products/dress2.jpeg
    - images/products/hills1.jpeg
    - images/products/hills2.jpeg
    - images/products/skt1.jpeg
    - images/products/skt2.jpeg
    - images/products/pants2.jpeg
    - images/m1.jpeg
    - images/back.jpg
    - images/lg.png
    - images/google.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat-Medium
      fonts:
      - asset: assets/Montserrat-Medium.ttf

  
    - family: LiuJianMaoCao-Regular
      fonts:
      - asset: assets/LiuJianMaoCao-Regular.ttf

    - family: Pacifico-Regular
      fonts:
      - asset: assets/Pacifico-Regular.ttf

    - family: Raleway-Regular
      fonts:
      - asset: assets/Raleway-Regular.ttf

    - family: VarelaRound-Regular
      fonts:
      - asset: assets/VarelaRound-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
